apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-limits
  annotations:
    policies.kyverno.io/title: Require Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      As a best practice, each container in a Pod should have resource limits configured.
      This policy validates that all containers have memory and cpu limits defined.
spec:
  validationFailureAction: {{ .Values.mode }}
  rules:
    - name: validate-limits
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: "CPU and memory limits are required."
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
