apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restricted-with-exceptions
spec:
  validationFailureAction: Enforce
#  validationFailureAction: Audit
  background: true

  rules:
    - name: restricted
      match:
        any:
          - resources:
              kinds:
                - Pod
#  rules:
#    - name: restricted
#      match:
#        any:
#          - resources:
#              kinds:
#                - Pod
#              namespaceSelector:
#               matchLabels:
#                  pod-security: restricted

      validate:
        podSecurity:
          level: restricted
          version: latest

          exclude:
            - controlName: Capabilities
              images:
                - my-registry/internal-agent:*
