apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-restricted-pss
  annotations:
    policies.kyverno.io/title: Restricted Pod Security Standards
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: restricted
      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        podSecurity:
          level: restricted
          version: latest
